import { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, NavLink, Route, Routes, useNavigate } from "react-router-dom";
import { AppBar, Box, Button, Card, CardContent, Container, CssBaseline, List, ListItem, ListItemText, Stack, TextField, ThemeProvider, Toolbar, Typography, createTheme } from "@mui/material";

const theme = createTheme({ palette: { primary: { main: "#4255d4" }, background: { default: "#f7f7f7" } }, shape: { borderRadius: 8 } });
type Task = { title: string; course: string };
const tasks: Task[] = [
  { title: "Лабораторная работа №1", course: "Frontend" },
  { title: "Домашнее задание по TypeScript", course: "Программирование" },
  { title: "Подготовить вопросы к занятию", course: "Базы данных" },
];

function Layout() { return <><AppBar position="sticky" color="inherit" elevation={0}><Toolbar sx={{ maxWidth: 1180, width: "100%", mx: "auto" }}><Stack direction="row" spacing={1}>{[["/", "Ленты"], ["/tasks", "Задания"], ["/schedule", "Расписание"], ["/planner", "Планер"], ["/notifications", "Уведомления"]].map(([to, label]) => <Button component={NavLink} to={to} key={to} sx={{ color: "text.secondary", "&.active": { color: "primary.main", fontWeight: 700 } }}>{label}</Button>)}</Stack></Toolbar></AppBar><Container maxWidth="lg" sx={{ py: 4 }}><Routes><Route path="/" element={<Dashboard />} /><Route path="/tasks" element={<Tasks />} /><Route path="/schedule" element={<Schedule />} /><Route path="/planner" element={<Planner />} /><Route path="/notifications" element={<Notifications />} /></Routes></Container></>; }
function Dashboard() { const nav = useNavigate(); return <><Typography variant="h4" fontWeight={800}>Ленты лабораторных и заданий</Typography><Typography color="text.secondary" sx={{ mt: 1, mb: 4 }}>Новые материалы по учебным каналам.</Typography><Stack direction={{ xs: "column", md: "row" }} spacing={2} sx={{ mb: 4 }}>{[["3", "Новых публикации"], ["5", "Заданий в работе"], ["2", "Ближайших срока"]].map(([n, t]) => <Card sx={{ flex: 1 }} key={t}><CardContent><Typography variant="h4" fontWeight={800}>{n}</Typography><Typography color="text.secondary">{t}</Typography></CardContent></Card>)}</Stack><Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 1 }}><Typography variant="h6" fontWeight={700}>Последние публикации</Typography><Button color="inherit" onClick={() => nav("/tasks")}>Все задания</Button></Stack><TaskList /></>; }
function TaskList() { return <Card><List>{tasks.map((task, i) => <ListItem key={task.title} divider={i < tasks.length - 1}><ListItemText primary={task.title} secondary={task.course} /></ListItem>)}</List></Card>; }
function Tasks() { const [title, setTitle] = useState(""); const [shown, setShown] = useState(tasks); return <><Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 4 }}><Box><Typography variant="h4" fontWeight={800}>Задания</Typography><Typography color="text.secondary">Лабораторные работы и домашние задания.</Typography></Box><Button variant="contained" onClick={() => document.getElementById("new-task")?.focus()}>+ Новое задание</Button></Stack><Stack direction="row" spacing={1} sx={{ mb: 3 }}><TextField id="new-task" size="small" label="Название задания" value={title} onChange={(e) => setTitle(e.target.value)} /><Button variant="outlined" onClick={() => { if (title.trim()) { setShown([{ title, course: "Домашние задания" }, ...shown]); setTitle(""); } }}>Добавить</Button></Stack><TaskListOverride tasks={shown} /></>; }
function TaskListOverride({ tasks: list }: { tasks: typeof tasks }) { return <Card><List>{list.map((task, i) => <ListItem key={`${task.title}-${i}`} divider={i < list.length - 1}><ListItemText primary={task.title} secondary={task.course} /></ListItem>)}</List></Card>; }
function Schedule() { return <><Typography variant="h4" fontWeight={800}>Расписание</Typography><Typography color="text.secondary" sx={{ mt: 1, mb: 4 }}>Ближайшие занятия и сроки сдачи.</Typography><TaskListOverride tasks={tasks} /></>; }
function Planner() { return <><Typography variant="h4" fontWeight={800}>Планер</Typography><Typography color="text.secondary" sx={{ mt: 1, mb: 4 }}>Ваш план работы на неделю.</Typography><Card><CardContent><Typography>Понедельник — лабораторная работа №1</Typography><Typography sx={{ mt: 2 }}>Среда — домашнее задание по TypeScript</Typography><Typography sx={{ mt: 2 }}>Пятница — проверка материалов</Typography></CardContent></Card></>; }
function Notifications() { return <><Typography variant="h4" fontWeight={800}>Уведомления</Typography><Typography color="text.secondary" sx={{ mt: 1, mb: 4 }}>Изменения по заданиям и каналам.</Typography><Card><List><ListItem divider><ListItemText primary="Опубликована новая лабораторная работа" secondary="Канал Frontend" /></ListItem><ListItem><ListItemText primary="Срок сдачи приближается" secondary="Домашнее задание по TypeScript" /></ListItem></List></Card></>; }
createRoot(document.getElementById("root")!).render(<StrictMode><ThemeProvider theme={theme}><CssBaseline /><BrowserRouter><Layout /></BrowserRouter></ThemeProvider></StrictMode>);
